spring.application.name=ong-animais

#Conexão com banco
spring.datasource.url=jdbc:postgresql://localhost:5432/ong_animais
spring.datasource.username=postgres
spring.datasource.password=sua_senha

#DDL - como o hibernate trata a estrutura do banco
spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true

#SQL no console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#Dialeto
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jackson.deserialization.fail-on-unknown-properties=true


